services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 80:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=piotr.sarnecki@yahoo.pl
      - PGADMIN_DEFAULT_PASSWORD=password